import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginBtn from './Login_btn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from './Logout_btn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="navbar mx-auto text-center">
          <Link href="/" className="logo">실험용 CRUD</Link>
          <Link href="/list">List</Link>
          {/* <LoginBtn></LoginBtn> */}
          {session ? <span>{session.user.name + ' 님 어서오세요'}<LogoutBtn /></span> : <LoginBtn />}
        </div>
        {children}
      </body>
    </html>
  )
}
