import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginBtn from './Login_btn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from './Logout_btn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  //console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar mx-auto text-center">
          <Link href="/" className="logo">미구현화면, List를 눌러주세요</Link>
          <Link href="/list">List</Link>
          {session!=null? <LogoutBtn />:<LoginBtn />}
        </div>
        {children}
      </body>
    </html>
  )
}
